const hu = {
  'site.title': 'Hófehérke és a ...',
  'site.subtitle': 'Egész estés meseelemzés felnőtteknek',
  'site.description': ' ',
  'site.keywords': ' ',

  'character.queen.title': 'Királynő',
  'character.snowwhite.title': 'Hófehérke',
  'character.stepmother.title': 'Mostoha',
  'character.king.title': 'Király',
  'character.prince.title': 'Herceg',
  'character.huntsman.title': 'Vadász',

  'story.asWeKnowIt.title': 'Ahogy ismerjük',
  'story.asWeKnowIt.desc': '...',

  'story.scene.beginning.king': 'Egyszer volt, holnem volt, volt egyszer egy király...',
  'story.scene.beginning.queen': '...és egy  királyné...',
  'story.scene.beginning.snowwhite': '...És született egy gyermekük, Hófehérke.',
  'story.scene.beginning.witch': 'A királyné meghalt, helyét a gonosz mostoha vette át. Ez a nő pont az ellentéte volt a királynőnek, ezért nemigen szeretjük.',
  'story.scene.beginning.huntsman': 'A gonosz mostoha felbérli a vadászt, hogy ölje meg Hófehérkét. A vadász kivételt tesz, megszegve ezzel munkaköri kötelességét.',
  'story.scene.beginning.prince': 'Hófehérke elmenekül, jön a törpés jelenet, aztán meg a herceg. A herceg kiszabadítja Hófehérkét a gonosz törpék közül, és frigyre kelnek. Ennyit a meséről dióhéjban.',

  'story.scene.sequel1': '<h3>A folytatás</h3><h4>Bárminemű hasonlóság valóságos személyekkel csak a véletlen műve...</h4><p>A mese elemzése során olykor végletesen eltávolodunk az eredeti történettől, majd onnan visszatekintve szemlélhetjük a történetet egy új nézőpontból. Ebben a grafikonos részben humorosnak szánt stílusban első gondolataimat vetettem le.</p><img src="/images/snowwhite/problems/14030ffbdff1b5a0761ba0b1c5af82d5.jpg" class="ui small left floated image" /><p>Nos, a mese véget ért, de egy másik elkezdődött. Hófehérke hosszú éveken át élt a herceg (a férje) mellett, főzött, mosott, takarított, és ezért cserébe... nem sok mindent kapott. Már nem szólították hófehérkének, noha királynő volt, meg egyben feleség, a jegyző “Karsainé Horváth Gizella” nevet jegyezte be a házassági anyakönyvbe, ahogy az lenni szokott. A hosszú évek alatt elveszítette bőre hófehér jellegét, plusz az utazások egzotikus országokba, meg az a rengeteg nikotin a cigiből... A tündérmese lassan-lassan szociodrámává alakult. És egy nap jött az igazi trauma:</p><p>egy másik királyságban megszületett “Hófehérke”</p>',

  'story.scene.sequel2': '<p>Az elemzés egy kritikus törésponthoz jutott. Mostantól nem egy de több mese vázlatát látjuk egyazon ábrán. Az Ex-Hófehérke kisodródik az eredeti mese fókuszából, és másik karakterként, u.n. Mostohaként tűnik fel újból. És a kör bezárul. És hogy mit történik ezután a mostohával – úgy értem ex-hófehérkével? Ugyanaz amit a mesében már hallottunk. De hogyan történhetett ez?</p>',

  'story.scene.sequel3': '<h3>A kör, A tükör</h3><img src="/images/mirror/4588eeda48a4fb1310f23aca6cec6696.jpg" class="ui small left floated image" /><p>A tükör, amely az előző tulajdonosát oly hűségesen szolgálta – és oly kegyetletlen dolgokra vette rá – Karsainé tulajdonában maradt, mivel apja élettársi viszonyban élt a banyával – mármint az ex-... mindegy. Egyszóval Hófehérke megörökölte a tükröt a gonosz mostohától. A tükör, amely a banyát őrületbe kergette, a fürdőszobában kapott helyet, sok örömet szerezve Hófehérkének. Legalábbis eleinte. Amikor a másik Hófehérke megszületett, a tükör detektálta a változást - mivel erre programozták, s mondta az igazat. Az egyetlen tökéletes Hófehérke illúziója ezzel végleg megszűnt létezni, kiderült, hogy csak mese volt az egész...</p><img src="/images/mirror/e2821a1da5469f09320aadcbd3c73e06.jpg" class="ui small right floated image" /><p>Senkinek nem esik jól, ha kiesik a kényelmes központi szerepből, hogy ő a világ közepe, a történet főhőse, a szeretett, a megbecsült, a jó karakter, akire csak csodálatos dolgok várhatnak. De megesik, és ha így adódik az fájó. A reakció általános: Csalódottság, féltékenység, düh, egyfajta gonoszság. És már kész is a banya. Hát még ha a tükör – a külvilágból érkező folyamatos megítélés is megerősíti... ördögi kör. A csapdába rekedt “gonosz királynő” úgy ítéli meg, hogy az “új jövevény” a bajok forrása, hisz amíg az nem volt, minden rendben volt. Úgy próbálja feloldani a konfliktust, hogy elpusztítaná azt a lényt, aki mit sem sejt arról, hogy ő bárkit bármiben akadályozna... Tudatán kívül egykori önmagát pusztítja el ezzel, ezáltal is egyre jobban eltávolodva a “Hófehérkétől” és közeledve a “banyához”</p>',

  'story.scene.sequel4': '<h3>A vadász</h3><p>A vadászról nem sokat mond a mese. Egyetlen feladata, hogy a “Gonosz királyné” parancsára ölje meg hófehérkét és hozza el annak kivágott szívét bizonyítékul. Nos egy szívről nehéz bárkit is azonosítani, így ez is szimbólikus: “törje össze a szívét”. Vegye el szépsége forrását, a naív, romlatlan szeretetet, lelke belső fényét, amely a szépségének valódi forrása.</p><p>Hogyan törje össze a szívét? Éjjel vigye ki az erdőbe, és ott... vegye elő a fegyverét, és döfje le, avagy célozzon és lőjön. Aztán vegye el a szívét, és tegye a gonosz elé bizonyítékul.</p><p>A vadász tehát nem afféle vadgazdálkodó szerepben jelenik meg, hanem inkább olyanban aki másra vadászik, úgy is mondhatnánk, p!#@vadász, hogyha nagyon egyértelműen be akarjuk sorolni... Így mindjárt jobban összeáll a kép:</p>',

  'story.scene.sequel5': '<p>Figyeljük meg, hogy kialakult 3 pár. Innen már nagyjából minden egyenesen következik majd. Középen a Hófehérke mese főszereplői, jobbra és balra másik 2 mese főszereplői. Balról fenn a “jó” karakterek, akik segítenek, jobbról lenn az ellenlábasok.</p><h3>Hárman párban?</h3><p>Jogosan lehetne mondani, hogy a mese nem így van, a király ott egyedül van a királyné halála okán, a vadász és a gonosz mostoha között pedig még csak élettársi kapcsolat sincs... Véleményem szerint a karakterek kibontása mégis erre az eredményre vezet, a szerepeket így lehet párosítani.</p><p>A vadász és a gonosz királyné kapcsolatára egyik legjobb bizonyíték, hogy a mese, mint egy jobb hollywoodi film, direkt nem tesz említést a köztük lévő kapcsolatról, hogy ne is sejtsük, ezáltal növelve a felismerés megdöbbentő erejét – ha eljön az ideje. Annyit tudni, hogy a gonosz tettben együttműködés kezdődik, de a vadász nem engedelmeskedik, ezért a gonosz királyné börtönbe zárja.</p><p>A feltételezés szerint a gonosz mostoha maga egykor Hófehérke volt. Akkor hát volt neki férje, a herceg, de férj nélkül érkezik a történetbe...</p>',

  'story.scene.sequel6': '<h3>A válás</h3><p>Tiszta sor, Hófehérke és a herceg elváltak. Így még érthetőbb miért olyan gonosz a mostoha. Hogy ő akart-e válni, vagy a herceg, azt nem tudni. Mindkettőjüknek volt oka rá bőven.</p><p>A herceg nem volt egy egyszerű eset... Eleinte odaadó volt, a csillagokat is odaígérte, de végül maradt egy lakótelepi lakás. A hétvégéket eleinte együtt töltötték, majd a herceg szívesebben sörözött a barátaival, és néha sokáig elmaradt... Már nem volt aki dícsérje Hófehérke csodás jellemvonásait, melyeket mind jól ismerünk, mert amikor együtt vacsoráztak, a herceg csak bámult maga elé a tányérba, és ha Hófehérke kérdezte valamiről, a válasz általában az volt, “most szeretnék nyugodtan enni, ha nem probléma”. Aztán volt, hogy több pénzt vitt, mint amennyit hozott, iszákosság, szerencsejáték, további kimaradások...</p>',

  'story.scene.sequel7': '<h3>A herceg transzformációja</h3><img src="/images/snowwhite/girlfriends/8fb991217a3562df7e0750a697eae6d5.jpg" class="ui medium left floated image" /><p>De Hófehérke sem volt egy egyszerű eset... Az csak természetes, hogy neki kellet lenni a középpontban, és a fő téma ezzel kellett hogy kapcsolatos legyen: ruhák, pipere, udvarhölgyek, csupa olyan téma ami a herceget hidegen hagyta.</p><p>Amikor a herceg a barátaival szeretett volna találkozni, Hófehérke nem repesett az örömtől, és ez a hercegben lelkifurdalást ébressztett. Bánatossá tette, hogy ő nem tudja úgy elszórakoztatni aráját, mint pl. a többi herceg a legutóbbi zenés estén, akik bezzeg felsorolták Hófehérke minden báját... Enyhe depresziójában, mikor egy keményen végigdolgozott nap után kedvese a vacsoránál kérdőre vonta, már azon merengett, hogy valóban ez-e az a Hófehérke, akit neki a mesében megírt módon feleségül kellett vennie. Mivel nem sikerült meggyőznie magát, és ebben Hófehérke sem volt segítségére, bánatában, hogy mekkora egy hülye, elvesztette a kontrollt életmódja felett, italba folytotta bánatát, Hófehérke mérhetetlen költekezését szerencsejátékból próbálta fedezni, és...</p>',

  'story.scene.sequel8': 'Amint az már majdnem nyilvánvaló volt, a herceg áttért – egyes források és rossz nyelvek szerint visszatért régi szokásához, és eleinte alkalomszerűen, majd mind gyakrabban vadászatra indult, mígnem ez az életmód rendszeressé vált, és végül úgy maradt. Így lett az egykor hercegből egy másik törénetben vadász. A nyíl jól szemlélteti a lezüllésének folyamatát.',

  'story.scene.sequel9': 'Az ábra ezen a ponton korrekcióra szorul. A herceget is nyilván anya szülte, és apja is kellett, hogy legyen. Úgy vélem, hogy a mesében a támadás Hófehérke ellen szimbólikus, tágabb értelemben véve pedig nem pusztán ellene irányul, hanem a boldog szeretetkapcsolat ellen, amit a sötét karakterek sikeresen el is pusztítottak, és ezáltal vehették fel jelenlegi formájukat. A mostoha és a vadász kapcsolata a válás, hogy nincs kapcsolat, ami pedig van, az bár ne is lenne inkább...',

  'story.scene.sequel10': '<h3>A látomás, vagy dezsavű?</h3><p>A királynővel kezdődik a mese, de nem sokat tudunk meg róla. Szeretnivaló, szép, egyetlen hibája csak hogy meghal. De ez is csak szimbólum, suprise-suprise: a királynő nem hal meg! Feláldozza önmagát, szerepébe temetkezik, ezért a tetszhalott állapot. Egyetlen szerepe pedig: létrehozni Hófehérkét</p><p>A királynő elábrándozik, avagy később álmot lát. Megfogalmazódik benne leendő gyemeke több tulajdonága: Hajszín, bűrszín, ajkainak színe. Genetikailag azonban csak olyan tulajdonságok örökölhetőek, amelyet az egyén – valamilyen formában -  maga is birtokol. A királynő – feltehetően maga is rendelkezett a hófehérkére jellemző tulajdonságokkal, elképzelhető, hogy azokat sorolta el, melyeket maga is kedvelt – egykori önmagában, amikor még ! Ö is Hófehérke volt!!!</p>',

  'story.scene.sequel11': 'Nem várt fordulat, mindenki a Hóferkéből alakult ki, még a Hófehérke is a Hófehérkéből lett...',

  'story.scene.sequel12': 'De a banyáról is ezt mondtuk, ez hogy lehet?',

  'story.scene.sequel13': 'Nos, itt belépünk a tudatalatti világába, elérkeztünk az archetípusokhoz, meg az ezotériához. A két ellentétes személyiség skizoid módon parallel evolvál, olykor transzlokálódik, vagy expressziója szuszpendálódik. (világos, nem?)',

  'story.scene.sequel14': '<h3>A szív</h3><p>Milyen volt a királynő? - Szivélyes. Milyen volt a mostoha? - Szívtelen. Mit akart tenni Hófehérkével? - Szívteleníttetni akarta.</p><h3>A szívtelen</h3><p>Miért volt szívtelen a mostoha? - Valószínűleg, mikor még ő is Hófehérke volt, a vadász őt is kicsalta az erdőbe, elővette fegyverét, és... ezt a szív bánta. Az is lehet, hogy további vadászok is megpróbálták megszerezni a szívét, mire már semmi sem maradt... Sőt, lehet, hogy arra a következretésre jutott, hogy ez így normális, és végül maga csalta ki a vadászokat az erdőbe. De ez nem tette boldoggá. A szépségért sok mindenre képes egy nő, még sebészeti beavatkozásokra is, nos, ő szívleszívást csináltatott magán, remélve, hogy sikeresebb lesz a férfiaknál, és valóban, a mese nem említi hogy csúf lett volna...</p><h3>Az öreg király</h3><p>A király még kimaradt, szerepvállalása, jellemzői megkérdőjelezhetőek. Hófehérke szerető apjaként, a királyné özvegyeként szeretnivaló, de amikor összeáll a gonosz mostohával, és hagyja, hogy  az Hófehérke ellen keljen, szánalmas áldozattá, tutyimutyi papucsférjjé válik. Ki ő valójában és honnan származik?</p>',

  'story.scene.sequel15': 'Ahogy az már várható volt, a maszkulin perszonák a  feminimekhez hasonlóan divergálnak. A vertikális a maszkulin, a horizontális direkció a feminim transzformációkat prezentálja. (Kérem, ez egy komoly, tudományos cikk...)',

  'story.scene.sequel16': '<h3>A hűs</h3><p>A király - az egykori herceg - egy példamutató karakter a szeretet megvalósításában. Ő nem vált el, mint a vadász, nem lett hős, hanem maradt hűs, hűséges. Jegelte vágyait, fékezte érzelmeit. (A mese télen kezdődik). Volt mit fékeznie, végig kellett néznie, ahogyan Hófehérke átalakul, feleségül vette a szeretett nőt, és azon találja magát, hogy a gonosz mostohával él. Mit tehet egy férfi egy szívtelen nő társaként? El kell érnie, hogy újból legyen szíve... szeretnie kellett.</p><h3>A szeretet</h3><p>Hogy tudta szeretni azt a gonosz banyát? A szeretet tisztán lát, nem dől be a felszínes jellemeknek, nem a pillanatnyi szereposztás alapján ítél, hogy éppen kinek mi jutott. A király karakter példát mutat türelmével, hogy akkor is szerepében marad, és fenntartja a szeretetét amikor körülötte minden összeomlik. Bánatos a viszontagságok miatt, de nem zavarja el a gonosz mostohát, majd csak akkor, mikor Hófehérke visszatért, célt ért tehát, a nélkül, hogy maga is gonosszá válna.</p>',

  'story.scene.sequel17': '<h3>Gonosz mostoha – Öreg király pár</h3><p>Az ábra egyik sarkába az “özvegyen maradt” király új kapcsolata került. Nehezen lehetne jó kapcsolatnak nevezni, de a történet határozott említést tesz a pár tagjainak összetartozásáról.</p><p>Amint a mostoha megjelenik, beköszönt a konfliktusos rész, a sötét időszak semmilyen szempontból nem termékeny. A királyné halott.</p><p>A király jelenléte irreleváns, sakkba szorul.</p><p>Hófehérke száműzve, a herceg még sehol.</p><p>A vadász pedig börönbe zárva...</p><p>De erre majd visszatérünk.</p>',

}
export default hu
