<ScrollSection {...props} id="story.storytelling.new-age">
      <h3>Újkori mesék</h3>
      <div>
        <p>Itt kell megjegyeznem, hogy Bécsben dolgozok, és napi szinten szembesülök a bibózó szabadság újabb és újabb kinyíló virágaival. Leginkább az egyik munkahelyi <a href="https://twitter.com/JaneFrankland/status/1004407114217984001?s=19">botrány</a> nyitotta fel szemem, amelyet magam nem értettem. Ma már jobban értem, de igazán sohasem fogom. Ezek után nem csoda, ha a régi mesék világába menekülök...</p>

        <p>Ezt a meseelemzést már a számítógép segítségével írom, nincs ebben semmi meglepő. Talán érdekesebb, hogy közvetlenül meg tudom osztani a világhálón, és bárki hozzáférhet, elolvashatja. Ami még ennél is érdekesebb, hogy korunk legnépszerűbb fejlesztői eszközének segítségével a Github-on tárolom és követem nyomon a változtatásokat. Ez egy külön világ, egyedi szabályokkal. Elméletileg programkódok menedzselésére szolgál, de az ideológia ide is begyűrűzik. Az az ideológia, hogy ideológiamentes. Ez nagyon fontos. Egy új, nyílt, szabad társadalmon alapuló világ szerveződik épp. Egyik legfőbb bázisa ennek az új struktúrának a fejlesztők hada, akik létrehozzák a virtuális valóságot, egy olyan (sötét) hálót, amibe végül a valóságos valóság is belegabalyodik majd. De egyelőre nincs baj, mert nagyon szép eszmék vezérlik a közösségek tagjait. Ilyen a mások elfogadása, kortól, bőrszíntől, ideológiától, vallástól, nemtől vagy szexuális beállítódottságtól függetlenül. Bár ezen meglepődtem, hiszen ha látott már valaki kódot, az tudja, hogy ilyen információkat igen nehéz kiolvasni belőle. Nem is a kódról van szó, hanem az ezt körítő kommunikációról, a valós emberekről. Annyira komolyan veszi a nyugati társadalom a nők egyenjogúsáágát, hogy támogatja a külön nőknek szóló fejlesztői közösségeket, meetupokat, ahol a feminizmus nem hogy megtűrt, de kívánatos jelenség. Meg kell jegyezni, hogy ez a feminizmus nem az a feminizmus ami a hatvanas években volt. Itt most sokkal inkább a leszbikusok jogairól, a cunilingusról, a menstruációhoz való jogról van szó. Ezek a körök elzárva is működhetnek, úgy értem, ez nem férfiaknak való téma, így ők ebből kizárhatóak, még a kód írásából is. A nők előjogaiért való harc egyre népszerűbb, egyre több olyan hivatalos weboldal van, mint a womentechmakers ahonnan ez a kép is származik.</p>
        <p><img className="ui fluid image" src="/images/story/woman.jpg" /></p>
        <p>Ez a kép az elsők közt jelent meg, mikor rákerestem. Az ilyan cégek jellemzően fellépnek a nők jogaiért, valamint a megkülönböztetés és a szexizmus ellen. Az előadó lányka felett olvasható korunk egyik legnagyobb világmárkájának neve.</p>
        <p>Csak én veszem észre hogy ezek tökök? De most komolyan? Senki sincs, aki kimondaná: Meztelen a király? Miféle álszent világot építünk? Az internetes adatforgalom több mint 3/4-e pornó, és ennek az adatforgalomnak a lebonyolításában komoly céges teljesítményre is szükség van, ez magától nem megy. Egy átlag modern kori nő, ahhoz, hogy önérzetes maradjon rengeteg munkát, pénzt, és fájdalmat vállal, hogy megfelelően öltözött, sminkezett, parfümözött, szőrtelenített és mittudom én még milyen legyen. De ezt már nem a férfiak kedvéért teszi. Meg tudom érteni, hisz a modern férfi puding. Lehet, hogy kigyúrt, de belül mégis puding és gyerek. Mit tud egy férfi ma, amit egy nő ne tudna? Ma már a nők a tökösek, büszkék az erejükre, a szellemi termékeikre, a karrierjükre, hogy önnáló dzsungelharcosok a betondzsungelben.</p>
        <p>A világ változik, az ideálok is változnak. A korábbi idálokat elítéljük, mint például a második világháború borzalmaihoz vezető ideálokat, melyet mellesleg a saját korában az egész német nép imádott, és ameikában is tervbe vették. Más, korábbi ideálok feledésbe merülnek.</p>
        <p>Amikor a tőkések és nemesek legelőször vasútvonalat akartak építeni, voltak kis csoportok, akik ellenáltak ennek, mert féltek, rosszabb lesz majd a világ. Most amikor ugyanazok a tőkések gazdaságtalan vasútvonalakat akarnak felszámolni a szép dombvidékeken, ugyanazok a kis csoportok könyörögnek, hogy ne szüntessék meg a vasútvonalat, mert félnek, rosszabb lesz majd a világ...</p>
        <p>Különösen fontosnak tartom a magyarság, de legalábbis a magyar nyelv szerepét ebben a korban (is). Az a nyugati világ akar kioktatni minket egyenjogúságból akik a fél, ha nem az egész világot leigázták és nyomorba, rabszolgasorba döntötték. Azok a latin alapú nyelvek ítélnek el minket a nemek hátrányos megkülönböztetésééert, amelyek még az asztal lábát is külön nemmel nevezik meg. Nőnem és hímnem nincs a magyar nyelvben, a fér-j megfér, a fele-ség a férfi jobbik fele.</p>
        <p>Úgy érzem, minthogy nincs más aki megtegye, nekünk magyaroknak kell, nekem személyesen kell rávilágítanom, hogy a nyugatiak nagy becsben tartott meséi kincsek, és ideje elővenni őket. Mert jobb volt az a világ, mint a mostani. A nyugati meséket jogosan vádolhatnám meg, hogy a keletiek koppintásai, az ősi mesék lecsupaszodott, eltorzult maradványai. De nem teszem, mert a mesék erről nem tehetnek, csak mi emberek. A Grimm mesék, a korban, kultúrában hozzánk legközelebb álló emlékek, az értelmezést itt érdemes kezdeni. Szép lenne saját, gyönyörő népmeséinket is ilyen formán elővenni, de félek, én még kevés vagyok ahhoz. A grimm meséken könnyebb fogást találni.</p>
      </div>
    </ScrollSection>
